### ISSUE TITLE
Coreelec: missing libopenmaxil.so

### ISSUE THREAD

**Issue by JeremyTheocharis** [skoglar/plugin.program.parsec#1]
Hi,

thank you for working on this add-on! 

I am recieving the following error message when trying to execute ./parsec:

`libopenmaxil.so: cannot open shared object file: No such file or directory`

The application does not start. I am using: 
`CoreELEC (official): 8.95.7 (S912.arm)` (on miniX neo u9-h with ARM architecture)

As far as I understood the missing library is raspberryPI specific. 

Do you have any idea how to resolve this issue?

Regards,
Jeremy

**Comment by skoglar** [comment]
Hey there,
For what I've read, openmax is indeed a specific library used on the [rpi rapsec build](https://blog.parsecgaming.com/the-thin-client-start-playing-pc-games-on-your-raspberry-pi-adb23a5ebd85), sadly, there isn't really any other arm builds to work with (besides the android version), so I dont really think getting the library installed will do you much good.

The only possible solution I can think of is going back to using android on your minix and using the [native android app](https://play.google.com/store/apps/details?id=tv.parsec.client) for parsec.

Have a nice week!

**Comment by JeremyTheocharis** [comment]
Thank you for your answer!

**Comment by SoulReaver-SS** [comment]
I'm getting this on Raspberry pi 4.
Is there a workaround for pi 4?
