### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by FrancisKunz** [skoglar/plugin.program.parsec#2]
The log-in process works fine, the stream is more than Ok but i can't get any sound either on HDMI, Headset or Bluetooth.

Any idea ?

I'm using Librelec latest version with Kodi 18

**Comment by skoglar** [comment]
The fix depends on your setup, if you are running on a Raspberry pi, the fix should be running this [script](https://github.com/skoglar/plugin.program.parsec/blob/master/audiofix.sh) which will activate alsa an then set it up to work with pulseaudio. If you're on LE Generic, it helps to start pulseaudio manually before running the addon
