### ISSUE TITLE
Parsec Crashes on first launch, following instructions exactly.

### ISSUE THREAD

**Issue by jackebennett91** [skoglar/plugin.program.parsec#3]
Tried re-installing parsec, re-installing kodi and new sd card with no luck.

Any suggestions? Sorry if this seems rather n00by

**Comment by horstle** [comment]
For me the Server ID changed multiple times already (at least when not using Parsec for a while), after which the addon crashes. Did you check your Server ID? Did you completely delete the settings?

**Comment by skoglar** [comment]
It seems the server ID is no longer needed to run the client. I will update the plugin soon to correct this issue. In the meantime and while it might be a hassle, a workaround would be running parsec through ssh like this:
```sh
cd /storage/.kodi/addons/plugin.program.parsec/resources/data
chmod +x parsec
./parsec
```
You will be prompted for a username and password, then you can select a server to play in.

**Comment by jackebennett91** [comment]
Thanks for the reply!

Apologies for me being very much a beginner when it comes to Linux: your
workaround works in terms of connecting to my desktop PC, and it shows
successful connection in the Parsec windows app, but I am a little lost
after this point - I have tried to launch to kodi parsec app, but it once
again crashes the OS which reboots everytime I try loading it.

Not sure if i'm missing something (bleedingly) obvious but I remain stuck,
and any advise you could give would be great.

Jack

**Comment by skoglar** [comment]
@jackebennett91 I was assuming once connected parsec would take over your screen, that doesnt seem to be the case. 

The "reboot" you see is the plugin stoping and restarting kodi on your OS, its supposed to do that and launch parsec in between, that will work once the update is released. In the meantime avoid using the plugin directly and do this instead:

on ssh:

```sh
#stop kodi while you play
systemctl stop kodi
#this will turn your screen black, dont panic
cd /storage/.kodi/addons/plugin.program.parsec/resources/data 
#skip the chmod if you already did it
chmod +x parsec
#run parsec
./parsec
#now follow the instructions and you should see your desktop
```

Once you finish playing you can either shut down the pi, running `poweroff` on your ssh console or restart kodi with `systemctl start kodi`. 

That is, in a nutshell, what the addon does for you. Good luck!

**Comment by jackebennett91** [comment]
Followed the above, Libreelec gets stuck on loading screen; windows parsec
app says client connected, but nothing showing on libreelec screen. Still
displaying "failed to add service - already in use" from ssh putty window.

Thanks for your help but there still appears to be this issue!

Jack

**Comment by kognor1982** [comment]
Hi,

Any updates yet?  The server id is gone.  But how do I auto login to my server?

**Comment by jackebennett91** [comment]
Not working on raspberry pi 4

**Comment by skoglar** [comment]
sadly, Parsec doesn't have official support for the rpi4 yet. Anyways, the latest changes in the client seemed to have killed my addon, I did some tests and while they do say you could use your [peer_id](https://support.parsecgaming.com/hc/en-us/articles/115002699012-Setting-Up-On-Raspberry-Pi-Raspbian-) to invoke the client headlessly (`parsecd peer_id=YOUR_PEER_ID`). I am currently getting no response from that command, nor am I seeing any connection requests. Might be a dependency issue, but thats out of this project's scope, at least for now
